# user.userServicePath: http://localhost:7900/simple/
server:
  port: 7901

spring:
  application:
    name: microserviceconsumer

logging:
  level:
    root: INFO
    com.shang: TRACE

eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/

security:
  basic:
    enabled: false

