server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false   # 不要向eureka注册实例
    fetchRegistry: false        # 不要想服务器拉取eureka注册表
    serviceUrl:
      defaultZone: http://user:123456@${eureka.instance.hostname}:${server.port}/eureka/

security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
