spring:
  application:
    name: microservice-consumer-feign

server:
  port: 9706

security:
  basic:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/

logging:
  level:
    com.shang.cloud.feign.MicroserviceprovideruserClient: DEBUG

execution.isolation.thread.timeoutInMilliseconds: 5000 #修改默认的超时时间

#logging:
#  level:
#    root: INFO
#    com.shang: INFO
#    com.shang.cloud.feign.MicroserviceprovideruserClient: DEBUG  # feign日志

