spring:
  application:
    name: microserviceprovideruserribbon



logging:
  level:
    root: INFO
    com.shang: TRACE

security:
  basic:
    enabled: false

###ribbon配置优先级: 1.配置文件、2.Java Conconfig、3.默认值
MICROSERVICEPROVIDERUSER:  ##服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡采集随机策略


---
spring:
  profiles: server1

server:
  port: 7904

eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    healthcheck:
        enabled: true
    serviceUrl:
          defaultZone: http://user:123456@localhost:8761/eureka/

---
spring:
  profiles: server2

server:
  port: 7905

eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    healthcheck:
        enabled: true
    serviceUrl:
          defaultZone: http://user:123456@localhost:8761/eureka/
