server:
  port: 7908

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    data: classpath:data.sql
    schema: classpath:schema.sql
  application:
    name: microserviceprovideruser    # 应用名称

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.shang: TRACE


eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/

security:
  basic:
    enabled: false

