spring:
  application:
    name: microservice-hystrix-turbine

server:
  port: 9709

security:
  basic:
    enabled: false

eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/

turbine:
  aggregator:
    clusterConfig: MICROSERVICEPROVIDERUSERRIBBON  # 访问单个应用的状态：http://localhost:9709/turbine.stream?cluster=MICROSERVICEPROVIDERUSERRIBBON
  app-config: MICROSERVICEPROVIDERUSERRIBBON
    
logging:
  level:
    root: INFO

execution.isolation.thread.timeoutInMilliseconds: 5000 #修改默认的超时时间
